#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "LEGEND" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0dlcnRTaG5haWRlcnMvU3VuZGF5VXNlcmJvdC9hcmNoaXZlL21haW4uemlw" | base64 -d
    elif [[ $UPSTREAM_REPO == "X" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0dlcnRTaG5haWRlcnMvU3VuZGF5VXNlcmJvdC9hcmNoaXZlL21haW4uemlw" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0dlcnRTaG5haWRlcnMvU3VuZGF5VXNlcmJvdC9hcmNoaXZlL21haW4uemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="catuserbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    CATPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $CATPATH
    echo "    Starting CatUserBot    "
    echo "
                        :'######:::::'###::::'########::::
                        '##... ##:::'## ##:::... ##..:::::
                         ##:::..:::'##:. ##::::: ##:::::::
                         ##:::::::'##:::. ##:::: ##:::::::
                         ##::::::: #########:::: ##:::::::
                         ##::: ##: ##.... ##:::: ##:::::::
                        . ######:: ##:::: ##:::: ##:::::::
                        :......:::..:::::..:::::..::::::::
    "

    echo "
    '##::::'##::'######::'########:'########::'########:::'#######::'########:
     ##:::: ##:'##... ##: ##.....:: ##.... ##: ##.... ##:'##.... ##:... ##..::
     ##:::: ##: ##:::..:: ##::::::: ##:::: ##: ##:::: ##: ##:::: ##:::: ##::::
     ##:::: ##:. ######:: ######::: ########:: ########:: ##:::: ##:::: ##::::
     ##:::: ##::..... ##: ##...:::: ##.. ##::: ##.... ##: ##:::: ##:::: ##::::
     ##:::: ##:'##::: ##: ##::::::: ##::. ##:: ##:::: ##: ##:::: ##:::: ##::::
    . #######::. ######:: ########: ##:::. ##: ########::. #######::::: ##::::
    :.......::::......:::........::..:::::..::........::::.......::::::..:::::
    "
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
